@hostname = localhost
@port = 5100
@api_url = http://{{hostname}}:{{port}}/api

###
GET {{api_url}}/router

###
POST {{api_url}}/Create
Content-Type: application/json

{
    "Volt":564646.6666666,
    "Current": 4646462.333334343245
}

###
GET {{api_url}}/Read

###
GET {{api_url}}/Read/2

###
PUT {{api_url}}/Update/2
Content-Type: application/json

{
    "Volt":120.0,
    "Current":20.0
}

###
PATCH  {{api_url}}/Update/3
Content-Type: application/json

{
    "Volt":60.0
}