
@hostname = localhost
@port = 4100

@url = http://{{hostname}}:{{port}}

###
GET {{url}}

// get -> metto risorsa
// post -> prendo risorsa
// put -> prendo dati e aggiorna con tutti i dati
// patch -> aggiorno solo quello che riscrivo
// delete -> cancello risorsa

###

GET {{url}}/login

###

GET {{url}}/dashboard

###

GET {{url}}/timeline

